#!/bin/sh

# This parameter will cause the shell to exit immediately if a simple command exits with a nonzero exit value.
set -e

echo "Running pre-push hook"

# If your project have the script of test, you can run it here
yarn test
